[build]
command = "wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_extended_0.50_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.50_Linux-64bit.tar.gz && ./hugo --gc --minify"
publish = "archive/public"

[build.environment]
DISABLE_AUTO_INSTALL = "true"
SKIP_DEPENDENCY_INSTALL = "true"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_extended_0.50_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.50_Linux-64bit.tar.gz && ./hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_extended_0.50_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.50_Linux-64bit.tar.gz && ./hugo -b $DEPLOY_PRIME_URL"

[[plugins]]
package = "netlify-plugin-a11y"

[plugins.inputs]
resultMode = "warn"
